sqlldr lms/oracle@wizbank_v47_db control=D:\temp\usergroup1_Entity.ctl log=D:\temp\usergroup1_Entity.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\usergroup2_UserGroup.ctl log=D:\temp\usergroup2_UserGroup.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\usergroup3_EntityRelation.ctl log=D:\temp\usergroup3_EntityRelation.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user1_Entity.ctl log=D:\temp\user1_Entity.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user2_RegUser.ctl log=D:\temp\user2_RegUser.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user3_RegUserExtension.ctl log=D:\temp\user3_RegUserExtension.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user4_acEntityRole.ctl log=D:\temp\user4_acEntityRole.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user5_EntityRelation.ctl log=D:\temp\user5_EntityRelation.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user6_EntityRelation.ctl log=D:\temp\user6_EntityRelation.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user7_EntityRelation.ctl log=D:\temp\user7_EntityRelation.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\user8_EntityRelation.ctl log=D:\temp\user8_EntityRelation.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\resfolder1_Objective.ctl log=D:\temp\resfolder1_Objective.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\resfolder2_ObjectiveAccess.ctl log=D:\temp\resfolder2_ObjectiveAccess.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\question1_Resources.ctl log=D:\temp\question1_Resources.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\question2_ResourceObjective.ctl log=D:\temp\question2_ResourceObjective.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\question3_Question.ctl log=D:\temp\question3_Question.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\question4_Interaction.ctl log=D:\temp\question4_Interaction.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course1_aeItem.ctl log=D:\temp\course1_aeItem.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course2_aeItemTemplate.ctl log=D:\temp\course2_aeItemTemplate.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course3_aeItemTemplate.ctl log=D:\temp\course3_aeItemTemplate.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course4_aeItemTemplate.ctl log=D:\temp\course4_aeItemTemplate.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course5_CourseCriteria.ctl log=D:\temp\course5_CourseCriteria.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course6_Resources.ctl log=D:\temp\course6_Resources.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course7_Course.ctl log=D:\temp\course7_Course.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course8_ResourcePermission.ctl log=D:\temp\course8_ResourcePermission.log
sqlldr lms/oracle@wizbank_v47_db control=D:\temp\course9_aeItemAccess.ctl log=D:\temp\course9_aeItemAccess.log
