bcp wbv50..Entity in D:\temp\usergroup1_Entity.txt -f D:\temp\usergroup1_Entity.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..UserGroup in D:\temp\usergroup2_UserGroup.txt -f D:\temp\usergroup2_UserGroup.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..EntityRelation in D:\temp\usergroup3_EntityRelation.txt -f D:\temp\usergroup3_EntityRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Entity in D:\temp\user1_Entity.txt -f D:\temp\user1_Entity.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..RegUser in D:\temp\user2_RegUser.txt -f D:\temp\user2_RegUser.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..RegUserExtension in D:\temp\user3_RegUserExtension.txt -f D:\temp\user3_RegUserExtension.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..acEntityRole in D:\temp\user4_acEntityRole.txt -f D:\temp\user4_acEntityRole.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..EntityRelation in D:\temp\user5_EntityRelation.txt -f D:\temp\user5_EntityRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..EntityRelation in D:\temp\user6_EntityRelation.txt -f D:\temp\user6_EntityRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..EntityRelation in D:\temp\user7_EntityRelation.txt -f D:\temp\user7_EntityRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..EntityRelation in D:\temp\user8_EntityRelation.txt -f D:\temp\user8_EntityRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Objective in D:\temp\resfolder1_Objective.txt -f D:\temp\resfolder1_Objective.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ObjectiveAccess in D:\temp\resfolder2_ObjectiveAccess.txt -f D:\temp\resfolder2_ObjectiveAccess.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Resources in D:\temp\question1_Resources.txt -f D:\temp\question1_Resources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ResourceObjective in D:\temp\question2_ResourceObjective.txt -f D:\temp\question2_ResourceObjective.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Question in D:\temp\question3_Question.txt -f D:\temp\question3_Question.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Interaction in D:\temp\question4_Interaction.txt -f D:\temp\question4_Interaction.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeCatalog in D:\temp\catalog1_aeCatalog.txt -f D:\temp\catalog1_aeCatalog.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNode in D:\temp\catalog2_aeTreeNode.txt -f D:\temp\catalog2_aeTreeNode.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeCatalogAccess in D:\temp\catalog3_aeCatalogAccess.txt -f D:\temp\catalog3_aeCatalogAccess.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeCatalogAccess in D:\temp\catalog4_aeCatalogAccess.txt -f D:\temp\catalog4_aeCatalogAccess.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNode in D:\temp\treenode1_aeTreeNode.txt -f D:\temp\treenode1_aeTreeNode.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNodeRelation in D:\temp\treenode2_aeTreeNodeRelation.txt -f D:\temp\treenode2_aeTreeNodeRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItem in D:\temp\course1_aeItem.txt -f D:\temp\course1_aeItem.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\course2_aeItemTemplate.txt -f D:\temp\course2_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\course3_aeItemTemplate.txt -f D:\temp\course3_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\course4_aeItemTemplate.txt -f D:\temp\course4_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..CourseCriteria in D:\temp\course5_CourseCriteria.txt -f D:\temp\course5_CourseCriteria.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Resources in D:\temp\course6_Resources.txt -f D:\temp\course6_Resources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Course in D:\temp\course7_Course.txt -f D:\temp\course7_Course.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ResourcePermission in D:\temp\course8_ResourcePermission.txt -f D:\temp\course8_ResourcePermission.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemAccess in D:\temp\course9_aeItemAccess.txt -f D:\temp\course9_aeItemAccess.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNode in D:\temp\course10_aeTreeNode.txt -f D:\temp\course10_aeTreeNode.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNodeRelation in D:\temp\course11_aeTreeNodeRelation.txt -f D:\temp\course11_aeTreeNodeRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNodeRelation in D:\temp\course12_aeTreeNodeRelation.txt -f D:\temp\course12_aeTreeNodeRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTargetRule in D:\temp\course13_aeItemTargetRule.txt -f D:\temp\course13_aeItemTargetRule.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTargetRuleDetail in D:\temp\course14_aeItemTargetRuleDetail.txt -f D:\temp\course14_aeItemTargetRuleDetail.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeLearningSoln in D:\temp\course15_aeLearningSoln.txt -f D:\temp\course15_aeLearningSoln.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItem in D:\temp\exam1_aeItem.txt -f D:\temp\exam1_aeItem.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\exam2_aeItemTemplate.txt -f D:\temp\exam2_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\exam3_aeItemTemplate.txt -f D:\temp\exam3_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTemplate in D:\temp\exam4_aeItemTemplate.txt -f D:\temp\exam4_aeItemTemplate.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..CourseCriteria in D:\temp\exam5_CourseCriteria.txt -f D:\temp\exam5_CourseCriteria.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Resources in D:\temp\exam6_Resources.txt -f D:\temp\exam6_Resources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Course in D:\temp\exam7_Course.txt -f D:\temp\exam7_Course.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ResourcePermission in D:\temp\exam8_ResourcePermission.txt -f D:\temp\exam8_ResourcePermission.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemAccess in D:\temp\exam9_aeItemAccess.txt -f D:\temp\exam9_aeItemAccess.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNode in D:\temp\exam10_aeTreeNode.txt -f D:\temp\exam10_aeTreeNode.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNodeRelation in D:\temp\exam11_aeTreeNodeRelation.txt -f D:\temp\exam11_aeTreeNodeRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeTreeNodeRelation in D:\temp\exam12_aeTreeNodeRelation.txt -f D:\temp\exam12_aeTreeNodeRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTargetRule in D:\temp\exam13_aeItemTargetRule.txt -f D:\temp\exam13_aeItemTargetRule.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeItemTargetRuleDetail in D:\temp\exam14_aeItemTargetRuleDetail.txt -f D:\temp\exam14_aeItemTargetRuleDetail.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeLearningSoln in D:\temp\exam15_aeLearningSoln.txt -f D:\temp\exam15_aeLearningSoln.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeApplication in D:\temp\applicationpendingcourse1_aeApplication.txt -f D:\temp\applicationpendingcourse1_aeApplication.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnApprovalList in D:\temp\applicationpendingcourse2_aeAppnApprovalList.txt -f D:\temp\applicationpendingcourse2_aeAppnApprovalList.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationpendingcourse3_aeAppnActnHistory.txt -f D:\temp\applicationpendingcourse3_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationpendingcourse4_aeAppnActnHistory.txt -f D:\temp\applicationpendingcourse4_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeApplication in D:\temp\applicationpendingexam1_aeApplication.txt -f D:\temp\applicationpendingexam1_aeApplication.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnApprovalList in D:\temp\applicationpendingexam2_aeAppnApprovalList.txt -f D:\temp\applicationpendingexam2_aeAppnApprovalList.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationpendingexam3_aeAppnActnHistory.txt -f D:\temp\applicationpendingexam3_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationpendingexam4_aeAppnActnHistory.txt -f D:\temp\applicationpendingexam4_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeApplication in D:\temp\applicationstudycourse1_aeApplication.txt -f D:\temp\applicationstudycourse1_aeApplication.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..trackingHistory in D:\temp\applicationstudycourse2_trackingHistory.txt -f D:\temp\applicationstudycourse2_trackingHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAttendance in D:\temp\applicationstudycourse3_aeAttendance.txt -f D:\temp\applicationstudycourse3_aeAttendance.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..courseEvaluation in D:\temp\applicationstudycourse4_courseEvaluation.txt -f D:\temp\applicationstudycourse4_courseEvaluation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationstudycourse5_aeAppnActnHistory.txt -f D:\temp\applicationstudycourse5_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationstudycourse6_aeAppnActnHistory.txt -f D:\temp\applicationstudycourse6_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeApplication in D:\temp\applicationstudyexam1_aeApplication.txt -f D:\temp\applicationstudyexam1_aeApplication.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..trackingHistory in D:\temp\applicationstudyexam2_trackingHistory.txt -f D:\temp\applicationstudyexam2_trackingHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAttendance in D:\temp\applicationstudyexam3_aeAttendance.txt -f D:\temp\applicationstudyexam3_aeAttendance.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..courseEvaluation in D:\temp\applicationstudyexam4_courseEvaluation.txt -f D:\temp\applicationstudyexam4_courseEvaluation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationstudyexam5_aeAppnActnHistory.txt -f D:\temp\applicationstudyexam5_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..aeAppnActnHistory in D:\temp\applicationstudyexam6_aeAppnActnHistory.txt -f D:\temp\applicationstudyexam6_aeAppnActnHistory.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroup in D:\temp\studygroup1_studyGroup.txt -f D:\temp\studygroup1_studyGroup.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupRelation in D:\temp\studygroup2_studyGroupRelation.txt -f D:\temp\studygroup2_studyGroupRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Resources in D:\temp\studygroup3_Resources.txt -f D:\temp\studygroup3_Resources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Module in D:\temp\studygroup4_Module.txt -f D:\temp\studygroup4_Module.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupRelation in D:\temp\studygroup5_studyGroupRelation.txt -f D:\temp\studygroup5_studyGroupRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupMember in D:\temp\studygroupmember1_studyGroupMember.txt -f D:\temp\studygroupmember1_studyGroupMember.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupMember in D:\temp\studygroupmember2_studyGroupMember.txt -f D:\temp\studygroupmember2_studyGroupMember.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupResources in D:\temp\studygroupresource1_studyGroupResources.txt -f D:\temp\studygroupresource1_studyGroupResources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..studyGroupRelation in D:\temp\studygroupresource2_studyGroupRelation.txt -f D:\temp\studygroupresource2_studyGroupRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..knowCatalog in D:\temp\knowcatalog1_knowCatalog.txt -f D:\temp\knowcatalog1_knowCatalog.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..knowQuestion in D:\temp\knowquestion1_knowQuestion.txt -f D:\temp\knowquestion1_knowQuestion.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..knowCatalogRelation in D:\temp\knowquestion2_knowCatalogRelation.txt -f D:\temp\knowquestion2_knowCatalogRelation.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..knowAnswer in D:\temp\knowanswer1_knowAnswer.txt -f D:\temp\knowanswer1_knowAnswer.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Resources in D:\temp\forum1_Resources.txt -f D:\temp\forum1_Resources.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Module in D:\temp\forum2_Module.txt -f D:\temp\forum2_Module.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ResourcePermission in D:\temp\forum3_ResourcePermission.txt -f D:\temp\forum3_ResourcePermission.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..ResourcePermission in D:\temp\forum4_ResourcePermission.txt -f D:\temp\forum4_ResourcePermission.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..forumTopic in D:\temp\forumtopic1_forumTopic.txt -f D:\temp\forumtopic1_forumTopic.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..forumMessage in D:\temp\forummessage1_forumMessage.txt -f D:\temp\forummessage1_forumMessage.fmt -E -S ws37 -U cyber -P wisdom
bcp wbv50..Message in D:\temp\message1_Message.txt -f D:\temp\message1_Message.fmt -E -S ws37 -U cyber -P wisdom